#!/usr/bin/env bash
# 0-custom_http_response_header

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx to add custom HTTP response header
sudo sed -i '/^server_name/ a \\n\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

