#!/usr/bin/env bash
# Display the number of bash processes

# Use pgrep to find the PIDs of processes containing the word "bash"
pids=$(pgrep "bash")

# Count the number of PIDs and display it
count=$(echo "$pids" | wc -w)
echo "$count"
