#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process.

# Find and kill the 4-to_infinity_and_beyond process
pids=$(pgrep -f "4-to_infinity_and_beyond.sh")
if [ -n "$pids" ]; then
    echo "Stopping 4-to_infinity_and_beyond..."
    kill -SIGINT "$pids"
else
    echo "4-to_infinity_and_beyond process not found."
fi
