#!/bin/bash

case "$1" in
  start)
    while true; do
      echo "I am alive!" >> /tmp/my_process
      sleep 2
    done
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 1
    ;;
esac
