#!/usr/bin/env bash
# This script displays hours from 0 to 12 and minutes from 1 to 59

hour=0
minute=1

while [ $hour -le 12 ]; do
  echo "Hour: $hour"
  while [ $minute -le 59 ]; do
    echo $minute
    minute=$((minute + 1))
  done
  minute=1
  hour=$((hour + 1))
done
